const asset=name=>`assets/showcase/${name}.webp`;
const shot=(name,alt,cls='')=>`<img class="product-shot ${cls}" src="${asset(name)}" alt="${alt}">`;
const phone=(name,alt,cls='')=>`<figure class="device phone-device ${cls}">${shot(name,alt)}</figure>`;
const desktop=(name,alt,cls='')=>`<figure class="device desktop-device ${cls}">${shot(name,alt)}</figure>`;
const scenes=[
 {eyebrow:'宿舍环境与维护 · 双端原型',title:'把环境线索，\n接到维护进度上',desc:'学生记录现场变化，维护人员承接安排、处理与复查。两端共享同一条事件进度。',visual:`<div class="overview-stage">${desktop('admin-workbench','管理端校园空间维护工作台真实网页截图')}${phone('student-home-high','学生端高湿环境首页真实网页截图')}</div>`,tags:['学生端','管理端','课程概念原型']},
 {eyebrow:'01 · 一条清楚的事件线',title:'从环境线索，到一次完整跟进',desc:'读数提供线索，反馈保留现场感受；安排、处理和复查都落在同一条事件线上。',visual:`<div class="flow-stage"><article><b>01</b><div class="crop crop-home">${shot('student-home-high','学生端环境首页局部真实截图')}</div><h3>查看环境</h3><p>读数与状态一眼可见</p></article><i>→</i><article><b>02</b><div class="crop crop-feedback">${shot('student-feedback','学生端反馈页局部真实截图')}</div><h3>记录情况</h3><p>位置、现象和联系意向</p></article><i>→</i><article><b>03</b><div class="crop crop-admin">${shot('admin-detail','管理端安排页局部真实截图')}</div><h3>维护跟进</h3><p>安排、授权、处理与复查</p></article></div>`},
 {eyebrow:'02 · 学生端环境首页',title:'一种结构，适应四种环境状态',desc:'偏干、适宜、偏湿和高湿共用同一信息层级；文字、图标、数值与颜色一起表达状态。',visual:`<div class="modes-stage"><div class="mode-grid">${[['dry','偏干','35%'],['comfortable','适宜','52%'],['humid','偏湿','68%'],['high','高湿','78%']].map(([key,label,value])=>`<article class="mode-tile ${key}"><div class="mode-crop">${shot(`student-home-${key}`,`学生端${label}状态真实网页截图`)}</div><span>${label}</span><strong>${value}</strong></article>`).join('')}</div>${phone('student-home-high','学生端高湿环境首页完整真实网页截图','mode-phone')}</div>`},
 {eyebrow:'03 · 学生端反馈',title:'把现场情况说清楚，\n不替学生下结论',desc:'表单先问位置与现象，再补充照片、联系和入室意向。没有诊断口号，也不把联系意向当成正式授权。',visual:`<div class="phone-detail-stage">${phone('student-feedback','学生端反馈页完整真实网页截图')}<div class="detail-crop feedback-detail">${shot('student-feedback','学生端反馈表单局部真实截图')}</div><aside><b>三组信息</b><span>现场情况</span><span>可选照片</span><span>联系与入室意向</span></aside></div>`},
 {eyebrow:'04 · 学生端进度',title:'现在到哪一步，\n下一步做什么',desc:'反馈、安排、处理、复查使用同一套阶段语言；历史默认收起，当前状态和下一步始终优先。',visual:`<div class="phone-detail-stage progress-stage">${phone('student-progress','学生端处理进度页完整真实网页截图')}<div class="detail-crop progress-detail">${shot('student-progress','学生端四阶段进度局部真实截图')}</div><aside><b>四个阶段</b><span>反馈</span><span>安排</span><span>处理</span><span>复查</span></aside></div>`},
 {eyebrow:'05 · 管理端工作台',title:'任务在前，\n校园空间在后',desc:'白色校园模型建立空间识别，房间、状态、更新时间和事件入口仍留在清楚的信息区。',visual:`<div class="desktop-stage">${desktop('admin-workbench','管理端校园空间维护工作台完整真实网页截图')}<div class="desktop-caption"><span><b>空间</b>12号楼 · 302室</span><span><b>任务</b>事件列表与下一步</span><span><b>边界</b>示意视图，不代表实际定位</span></div></div>`},
 {eyebrow:'06 · 安排与授权',title:'安排现场查看，\n也守住入室边界',desc:'负责人、时间、查看范围与授权核实保持在同一上下文。未确认授权可以保存草稿，但不能执行入室查看。',visual:`<div class="desktop-stage detail-stage">${desktop('admin-detail','管理端事件安排与入室授权完整真实网页截图')}<div class="side-note"><span>授权未确认</span><strong>可存草稿<br>不能执行</strong><p>业务阻断由流程规则决定，不靠视觉警告代替。</p></div></div>`},
 {eyebrow:'07 · 处理与复查',title:'事实、行动和未知项，\n各自有位置',desc:'处理记录不写成结论口号；学生反馈与工作人员复查共同构成本次闭环，再次出现时仍可继续跟进。',visual:`<div class="closure-stage">${desktop('admin-process','管理端处理与复查完整真实网页截图')}${phone('student-progress','学生端结案与重新跟进真实网页截图')}<div class="closure-line"><span>现场记录</span><i>→</i><span>学生反馈</span><i>→</i><span>复查结案</span></div></div>`}
];
let current=Math.min(8,Math.max(1,Number(new URLSearchParams(location.search).get('scene'))||1));
const frame=document.querySelector('#scene'),count=document.querySelector('#scene-count');
function render(push=false){const s=scenes[current-1];document.body.classList.toggle('export-mode',new URLSearchParams(location.search).has('export'));frame.innerHTML=`<article class="scene scene-${current}"><div class="scene-copy"><p class="scene-eyebrow">${s.eyebrow}</p><h1>${s.title}</h1><p class="scene-desc">${s.desc}</p>${s.tags?`<div class="scene-tags">${s.tags.map(t=>`<span>${t}</span>`).join('')}</div>`:''}</div><div class="scene-visual">${s.visual}</div><footer><span>宿舍环境与维护</span><span class="scene-number">${String(current).padStart(2,'0')} / 08</span><nav aria-label="打开原型"><a href="index.html" target="_blank" rel="noopener">打开学生端</a><a href="admin.html" target="_blank" rel="noopener">打开管理端</a></nav></footer></article>`;count.textContent=`${current} / 8`;if(push){const url=new URL(location.href);url.searchParams.set('scene',current);history.pushState({scene:current},'',url);}document.title=`${current}/8 · ${s.title.replace('\n','')} · 宿舍环境与维护`;}
function go(step){current=(current-1+step+scenes.length)%scenes.length+1;render(true);}
document.addEventListener('click',event=>{const button=event.target.closest('[data-go]');if(button)go(button.dataset.go==='next'?1:-1);});
document.addEventListener('keydown',event=>{if(event.key==='ArrowRight')go(1);if(event.key==='ArrowLeft')go(-1);});
window.addEventListener('popstate',()=>{current=Math.min(8,Math.max(1,Number(new URLSearchParams(location.search).get('scene'))||1));render();});
render();
