const asset=name=>`assets/showcase/${name}.webp`;
const shot=(name,alt,cls='')=>`<img class="product-shot ${cls}" src="${asset(name)}" alt="${alt}">`;
const devices=(mobile,desktop,extra='')=>`<div class="device-stage ${extra}"><figure class="device desktop-device">${shot(desktop,'宿舍环境与维护管理端真实网页截图')}</figure><figure class="device phone-device">${shot(mobile,'宿舍环境与维护学生端真实网页截图')}</figure></div>`;
const scenes=[
 {format:'wide',eyebrow:'宿舍环境与维护 · 双端原型',title:'把环境线索，\n接到维护进度上',desc:'学生记录现场变化，维护人员承接安排、处理与复查。两端共享同一条事件进度。',visual:devices('student-home','admin-workbench','overview-devices'),tags:['学生端','管理端','课程概念原型']},
 {format:'portrait',eyebrow:'01 · 一条清楚的事件线',title:'从看到变化，到完成一次跟进',desc:'环境读数只提供线索；反馈、现场事实和复查记录各自保留，不把判断交给一条数字。',visual:`<div class="relation-flow"><article><span>01</span>${shot('student-home','学生端环境首页真实网页截图')}<h3>查看环境</h3><p>读数与现场感受并列</p></article><article><span>02</span>${shot('student-feedback','学生端反馈页真实网页截图')}<h3>记录情况</h3><p>描述位置、现象与联系意向</p></article><article><span>03</span>${shot('admin-detail','管理端事件安排页真实网页截图')}<h3>维护跟进</h3><p>从安排与授权进入现场处理</p></article></div>`},
 {format:'portrait',eyebrow:'02 · 学生端',title:'先看懂房间现在的环境',desc:'78% 是唯一主焦点。温度、24小时趋势、设备状态和更新时间都靠近它，减少来回寻找。',visual:`<div class="feature-layout phone-focus"><figure class="device phone-device">${shot('student-home','学生端环境首页真实网页截图')}</figure><aside class="feature-notes"><span>环境读数</span><strong>78%</strong><p>温湿度是环境线索，不替代现场判断。</p><hr><span>当前事件</span><p>首页直接显示状态与下一步入口。</p></aside></div>`},
 {format:'portrait',eyebrow:'03 · 学生端',title:'把现场情况说清楚',desc:'按“看到什么—现场照片—联系与入室意向”分组；不增加诊断，也不把学生意向当成正式授权。',visual:`<div class="feature-layout phone-focus reverse"><figure class="device phone-device">${shot('student-feedback','学生端反馈页真实网页截图')}</figure><aside class="feature-notes"><span>分组填写</span><h3>位置与现象优先</h3><p>照片选填，最多一张演示图片。</p><hr><span>边界说明</span><p>学生意向与入室授权分别核实。</p></aside></div>`},
 {format:'portrait',eyebrow:'04 · 学生端',title:'现在到哪一步，下一步做什么',desc:'四阶段状态条在两端使用同一套映射。完整历史默认收起，当前行动始终在前。',visual:`<div class="feature-layout phone-focus"><figure class="device phone-device">${shot('student-progress','学生端处理进度页真实网页截图')}</figure><aside class="feature-notes"><span>四个阶段</span><h3>反馈 · 安排 · 处理 · 复查</h3><p>文字、图标和连线共同表达状态。</p><hr><span>进度记录</span><p>结案后仍可保留历史并重新跟进。</p></aside></div>`},
 {format:'portrait',eyebrow:'05 · 管理端',title:'任务在前，校园空间在后',desc:'白色校园模型只帮助建立空间识别。房间、状态、更新时间和事件入口都留在信息区，不在图上虚构精确坐标。',visual:`<div class="desktop-feature"><figure class="device desktop-device">${shot('admin-workbench','管理端校园空间工作台真实网页截图')}</figure><div class="fact-strip"><span><b>空间</b>12号楼 · 302室</span><span><b>任务</b>待接手 · 待安排 · 待复查</span><span><b>边界</b>概念示意，不代表实际定位</span></div></div>`},
 {format:'portrait',eyebrow:'06 · 安排与授权',title:'安排现场查看，也守住入室边界',desc:'负责人、时间、查看范围和授权核实在同一上下文中完成。未确认授权可以保存草稿，但不能执行入室查看。',visual:`<div class="desktop-feature paired"><figure class="device desktop-device">${shot('admin-detail','管理端事件安排页真实网页截图')}</figure><figure class="device phone-device">${shot('student-progress','学生端处理进度页真实网页截图')}</figure><div class="callout"><span>授权未确认</span><strong>可存草稿，不能执行</strong></div></div>`},
 {format:'portrait',eyebrow:'07 · 处理与复查',title:'事实、行动和未知项，各自有位置',desc:'处理记录不写成结论口号；学生复查和工作人员复查共同构成本次闭环，问题再次出现仍可继续跟进。',visual:`<div class="desktop-feature paired review-pair"><figure class="device desktop-device">${shot('admin-process','管理端处理与复查页真实网页截图')}</figure><figure class="device phone-device">${shot('student-progress','学生端处理进度页真实网页截图')}</figure><div class="callout"><span>一次完整跟进</span><strong>记录 → 反馈 → 复查</strong></div></div>`}
];
let current=Math.min(8,Math.max(1,Number(new URLSearchParams(location.search).get('scene'))||1));
const frame=document.querySelector('#scene'),count=document.querySelector('#scene-count');
function render(push=false){const s=scenes[current-1];document.body.dataset.format=s.format;document.body.classList.toggle('export-mode',new URLSearchParams(location.search).has('export'));frame.innerHTML=`<article class="scene scene-${current}" data-format="${s.format}"><div class="scene-copy" data-safe="copy"><p class="scene-eyebrow">${s.eyebrow}</p><h1>${s.title}</h1><p class="scene-desc">${s.desc}</p>${s.tags?`<div class="scene-tags">${s.tags.map(t=>`<span>${t}</span>`).join('')}</div>`:''}</div><div class="scene-visual" data-safe="visual">${s.visual}</div><footer><span>宿舍环境与维护</span><span class="scene-number">${String(current).padStart(2,'0')} / 08</span><nav aria-label="打开原型"><a href="index.html" target="_blank" rel="noopener">打开学生端</a><a href="admin.html" target="_blank" rel="noopener">打开管理端</a></nav></footer></article>`;count.textContent=`${current} / 8`;if(push){const url=new URL(location.href);url.searchParams.set('scene',current);history.pushState({scene:current},'',url);}document.title=`${current}/8 · ${s.title} · 宿舍环境与维护`;}
function go(step){current=(current-1+step+scenes.length)%scenes.length+1;render(true);}
document.addEventListener('click',event=>{const button=event.target.closest('[data-go]');if(button)go(button.dataset.go==='next'?1:-1);});
document.addEventListener('keydown',event=>{if(event.key==='ArrowRight')go(1);if(event.key==='ArrowLeft')go(-1);});
window.addEventListener('popstate',()=>{current=Math.min(8,Math.max(1,Number(new URLSearchParams(location.search).get('scene'))||1));render();});
render();
